In [1]:
import pyfftw
import numpy as np

In [2]:
d = pyfftw.empty_aligned(4, dtype='complex128')
e = pyfftw.empty_aligned(4, dtype='complex128')
f = pyfftw.empty_aligned(4, dtype='complex128')
fft_object = pyfftw.FFTW(d, e)

In [3]:
fft_object.input_array is d # get the input array from the object

True

In [4]:
f[:] = np.array([1, 2, 3, 4]) # Add some data to f
fft_object(f)

array([10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [5]:
print(np.fft.fft(f)) #we can see the equivalence

[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [6]:
import splinv

In [7]:
a = pyfftw.empty_aligned((5, 5), dtype='complex128')
b = pyfftw.empty_aligned((5, 5), dtype='complex128')

# Over the both axes
fft_object_c = pyfftw.FFTW(a, b, axes=(0,1))

In [17]:
a = np.mgrid[:5, :5][0]
a_trans = np.fft.fft2(a)

In [18]:
print(np.fft.ifft2(a_trans))
print(a)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [4.+0.j 4.+0.j 4.+0.j 4.+0.j 4.+0.j]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [19]:
print(a_trans)

[[ 50.  +0.j           0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5+17.20477401j   0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5 +4.0614962j    0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5 -4.0614962j    0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5-17.20477401j   0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]]


In [20]:
print(fft_object_c(a,b))

[[ 50.  +0.j           0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5+17.20477401j   0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5 +4.0614962j    0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5 -4.0614962j    0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]
 [-12.5-17.20477401j   0.  +0.j           0.  +0.j
    0.  +0.j           0.  +0.j        ]]


In [21]:
fft_object_c(a)

array([[ 50.  +0.j        ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5+17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5 +4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5 -4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5-17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ]])

It seems you can run fft_object multiple times without having the input to interfere with the performance

In [22]:
fft_object_c(a)

array([[ 50.  +0.j        ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5+17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5 +4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5 -4.0614962j ,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ],
       [-12.5-17.20477401j,   0.  +0.j        ,   0.  +0.j        ,
          0.  +0.j        ,   0.  +0.j        ]])