In [1]:
import splinv
import numpy as np
import h5py
from configparser import ConfigParser
from splinv import utility
from astropy.io import fits

In [2]:
configName  =   'prepare_simulator.ini'
parser      =   ConfigParser()
parser.read(configName)

['prepare_simulator.ini']

In [3]:
simulator = utility.Simulator(parser)
print(len(simulator.prepare_argument(np.array([14.8,14.8]), ['nfw','cuspy'], np.array([4,4]), [True, False])))

400


In [4]:
arg1 = simulator.prepare_argument(np.array([14.8,14.8]), ['nfw','cuspy'], np.array([4,4]), [True, False])[0]
arg2 = simulator.prepare_argument(np.array([14.8,14.8]), ['nfw','cuspy'], np.array([4,4]), [True, False])[210]

In [5]:
#simulator.create_files()

In [6]:
result1 = simulator.simulate(arg1)
result2 = simulator.simulate(arg2)

nfw
noisy reconstruction
preparing numerical frames!!!!


KeyboardInterrupt: 

In [7]:
input_redshift = np.zeros(simulator.shape_basic_input)
input_a_over_c = np.zeros(simulator.shape_basic_input)
true_mass      = np.zeros(simulator.shape_basic_input)
simulated_mass = np.zeros(simulator.shape_basic_simulation_result)
same_redshift  = np.zeros(simulator.shape_basic_simulation_result,dtype=bool)
mass_bias = np.zeros(simulator.shape_basic_simulation_result)
simulated_redshift = np.zeros(simulator.shape_basic_simulation_result)
dmapper_w = np.zeros(simulator.shape_detail_simulation_result)
alpha_R = np.zeros(simulator.shape_detail_simulation_result)
input_shear = np.zeros(simulator.shape_detail_input,dtype=np.complex64)

In [8]:
# z_index = result1[0]
# a_over_c_index = result1[1]
# trial_index = result1[2]
# input_redshift[z_index,a_over_c_index] = simulator.z_samp[z_index]
# simulated_mass[z_index,a_over_c_index,trial_index] = result1[7]
# alpha_R[z_index,a_over_c_index,trial_index,:,:,:] = result1[9]









In [10]:
str(np.prod(input_shear.shape[1:][::-1]))+'D'

'460800D'

In [11]:
input_shear.shape

(10, 10, 2, 10, 48, 48)

In [13]:
dim_basic_input = str(simulator.shape_basic_input[1:][::-1])
n_basic_input  = str(np.prod(simulator.shape_basic_input[1:]))
dim_basic_simulation_result = str(simulator.shape_basic_simulation_result[1:][::-1])
n_basic_simulation_result  = str(np.prod(simulator.shape_basic_simulation_result[1:]))
dim_detail_input = str(simulator.shape_detail_input[1:][::-1])
n_detail_input = str(np.prod(simulator.shape_detail_input[1:]))
dim_detail_simulation_result = str(simulator.shape_detail_simulation_result[1:][::-1])
n_detail_simulation_result = str(np.prod(simulator.shape_detail_simulation_result[1:]))

c1 = fits.Column(name='input_redshift',      array= input_redshift,      format=n_basic_input+'E',dim=dim_basic_input)
c2 = fits.Column(name='input_a_over_c',      array= input_a_over_c,      format=n_basic_input+'E',dim=dim_basic_input)
c3 = fits.Column(name='true_mass',           array= true_mass,           format=n_basic_input+'D',dim=dim_basic_input)
c4 = fits.Column(name='simulated_mass',      array= simulated_mass,      format=n_basic_simulation_result+'D',dim=dim_basic_simulation_result)
c5 = fits.Column(name='same_redshift',       array= same_redshift,       format=n_basic_simulation_result+'L',dim=dim_basic_simulation_result)
c6 = fits.Column(name='mass_bias',           array= mass_bias,           format=n_basic_simulation_result+'D',dim=dim_basic_simulation_result)
c7 = fits.Column(name='simulated_redshift',  array= simulated_redshift,  format=n_basic_simulation_result+'E',dim=dim_basic_simulation_result)
c8 = fits.Column(name='dmapper_w',           array= dmapper_w,           format=n_detail_simulation_result+'D',dim=dim_detail_simulation_result)
c9 = fits.Column(name='alpha_R',             array= alpha_R,             format=n_detail_simulation_result+'D',dim=dim_detail_simulation_result)
c10 = fits.Column(name='input_shear',        array= input_shear,         format=n_detail_input+'C',dim=dim_detail_input)

In [14]:
t = fits.BinTableHDU.from_columns([c1,c2,c3,c4,c5,c6,c7,c8,c9,c10])
t.writeto('table3.fits')

In [19]:
test = fits.open('table3.fits',mode='update')
data = test[1].data
data['true_mass']

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
data['true_mass'][3,5] = 1

In [21]:
data['true_mass']

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
test.close()

In [23]:
test = fits.open('table3.fits')
data = test[1].data
data['true_mass']

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])